name: Docker Image CI

on:
  workflow_dispatch:

jobs:
 
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . -t admin44449999/access
    - name: login
      run: docker login -u admin44449999 -p Aaryanaryan && docker push admin44449999/access
